spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ariadne}
    username: ${DB_USERNAME:ariadne}
    password: ${DB_PASSWORD:ariadne-local}

    hikari:
      pool-name: AriadneHikariPool
      maximum-pool-size: ${DB_POOL_MAX_SIZE:10}
      connection-timeout: ${DB_POOL_CONNECTION_TIMEOUT:5000}
      validation-timeout: ${DB_POOL_VALIDATION_TIMEOUT:1000}

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: validate

ariadne:
  credential:
#    encryption-key: ${ARIADNE_CREDENTIAL_ENCRYPTION_KEY}
    encryption-key: AQIDBAUGBwgJCgsMDQ4PEBESExQVFhcYGRobHB0eHyA=